import { Offer, CategoryItem, StoreItem } from '@/types/offer';
import { TelegramSource, AdminMetrics } from '@/types/admin';

export const MOCK_CATEGORIES: CategoryItem[] = [
  { name: 'Todas', slug: 'todas', icon: 'Sparkles', count: 24 },
  { name: 'Eletrônicos', slug: 'eletronicos', icon: 'Smartphone', count: 8 },
  { name: 'Informática', slug: 'informatica', icon: 'Laptop', count: 6 },
  { name: 'Games', slug: 'games', icon: 'Gamepad2', count: 4 },
  { name: 'Casa & Cozinha', slug: 'casa-e-cozinha', icon: 'Home', count: 5 },
  { name: 'TV & Áudio', slug: 'tv-e-audio', icon: 'Tv', count: 4 },
  { name: 'Moda & Calçados', slug: 'moda-e-calcados', icon: 'Shirt', count: 3 },
  { name: 'Beleza & Saúde', slug: 'beleza-e-saude', icon: 'HeartPulse', count: 2 },
];

export const MOCK_STORES: StoreItem[] = [
  { name: 'Amazon', slug: 'amazon', count: 12 },
  { name: 'Mercado Livre', slug: 'mercado-livre', count: 8 },
  { name: 'Kabum', slug: 'kabum', count: 6 },
  { name: 'Magalu', slug: 'magalu', count: 5 },
  { name: 'Shopee', slug: 'shopee', count: 4 },
  { name: 'Samsung', slug: 'samsung', count: 3 },
  { name: 'Casas Bahia', slug: 'casas-bahia', count: 2 },
];

// Ofertas já publicadas na vitrine pública
export const MOCK_OFFERS: Offer[] = [
  {
    id: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    title: 'Smart TV 55" 4K UHD Samsung Crystal com Gaming Hub e Alexa Integrada',
    price_current: 2199.00,
    price_original: 3499.00,
    discount_pct: 37,
    store: 'Amazon',
    category: 'tv-e-audio',
    image_url: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=600&auto=format&fit=crop&q=80',
    original_link: 'https://www.amazon.com.br/dp/B0CX8R1234?tag=canal_origem_99',
    affiliate_link: 'https://www.amazon.com.br/dp/B0CX8R1234?tag=promoradar-20',
    telegram_msg_id: 10420,
    source_name: 'Promos VIP Tech',
    status: 'published',
    published_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    coupon_code: 'TV150',
    installments: '10x de R$ 219,90 sem juros',
    free_shipping: true,
    temperature: 342,
  },
  {
    id: 'a12b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d',
    title: 'Console PlayStation 5 Slim Edição Digital com 2 Jogos (Returnal + Ratchet & Clank)',
    price_current: 3199.90,
    price_original: 3999.90,
    discount_pct: 20,
    store: 'Kabum',
    category: 'games',
    image_url: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=600&auto=format&fit=crop&q=80',
    original_link: 'https://www.kabum.com.br/produto/499876?origem=telegram_grupo_promo',
    affiliate_link: 'https://www.kabum.com.br/produto/499876?tag=promoradar-20',
    telegram_msg_id: 10421,
    source_name: 'Radar Gamer BR',
    status: 'published',
    published_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    coupon_code: 'PLAY200',
    installments: '10x de R$ 319,99 sem juros',
    free_shipping: true,
    temperature: 518,
  },
  {
    id: 'b23c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e',
    title: 'Smartphone Samsung Galaxy S24 Ultra 5G 256GB Titânio Cinza 12GB RAM Câmera Quádrupla',
    price_current: 5499.00,
    price_original: 9999.00,
    discount_pct: 45,
    store: 'Mercado Livre',
    category: 'eletronicos',
    image_url: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&auto=format&fit=crop&q=80',
    original_link: 'https://mercadolivre.com.br/sec/s24ultra?p=outro_afiliado_telegram',
    affiliate_link: 'https://mercadolivre.com.br/sec/s24ultra?tag=promoradar-20',
    telegram_msg_id: 10422,
    source_name: 'Promos VIP Tech',
    status: 'published',
    published_at: new Date(Date.now() - 80 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 100 * 60 * 1000).toISOString(),
    coupon_code: 'GALAXY500',
    installments: '10x de R$ 549,90 sem juros',
    free_shipping: true,
    temperature: 842,
  },
  {
    id: 'c34d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f',
    title: 'Fritadeira Elétrica Air Fryer Mondial Grand Family 5.5L Inox com Timer',
    price_current: 289.90,
    price_original: 549.90,
    discount_pct: 47,
    store: 'Magalu',
    category: 'casa-e-cozinha',
    image_url: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=600&auto=format&fit=crop&q=80',
    original_link: 'https://www.magazineluiza.com.br/air-fryer-mondial-55l?seller=canal_tg',
    affiliate_link: 'https://www.magazineluiza.com.br/air-fryer-mondial-55l?tag=promoradar-20',
    telegram_msg_id: 10423,
    source_name: 'Achados & Cupons BR',
    status: 'published',
    published_at: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 140 * 60 * 1000).toISOString(),
  },
  {
    id: 'd45e6f7a-8b9c-0d1e-2f3a-4b5c6d7e8f9a',
    title: 'Monitor Gamer AOC Hero 24" IPS 165Hz 1ms FreeSync Premium Ajuste de Altura',
    price_current: 749.00,
    price_original: 1299.00,
    discount_pct: 42,
    store: 'Kabum',
    category: 'informatica',
    image_url: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&auto=format&fit=crop&q=80',
    original_link: 'https://www.kabum.com.br/produto/monitor-aoc-hero-24?afiliado_tg=123',
    affiliate_link: 'https://www.kabum.com.br/produto/monitor-aoc-hero-24?tag=promoradar-20',
    telegram_msg_id: 10424,
    source_name: 'Radar Gamer BR',
    status: 'published',
    published_at: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 200 * 60 * 1000).toISOString(),
  },
  {
    id: 'e56f7a8b-9c0d-1e2f-3a4b-5c6d7e8f9a0b',
    title: 'Fone de Ouvido Bluetooth JBL Tune 520BT com Bateria de até 57h e Graves Puros',
    price_current: 179.90,
    price_original: 299.00,
    discount_pct: 40,
    store: 'Amazon',
    category: 'tv-e-audio',
    image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
    original_link: 'https://www.amazon.com.br/dp/B0BX9T1234?tag=bot_ofertas_55',
    affiliate_link: 'https://www.amazon.com.br/dp/B0BX9T1234?tag=promoradar-20',
    telegram_msg_id: 10425,
    source_name: 'Promos VIP Tech',
    status: 'published',
    published_at: new Date(Date.now() - 240 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 260 * 60 * 1000).toISOString(),
  },
];

// Fila de curadoria com ofertas PENDENTES capturadas automaticamente do Telegram
export const MOCK_PENDING_OFFERS: Offer[] = [
  {
    id: 'pend-001',
    title: 'Placa de Vídeo RTX 4060 Ti 8GB GDDR6 Galax 1-Click OC com DLSS 3 e Ray Tracing',
    price_current: 2399.00,
    price_original: 3299.00,
    discount_pct: 27,
    store: 'Kabum',
    category: 'informatica',
    image_url: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=600&auto=format&fit=crop&q=80',
    original_link: 'https://www.kabum.com.br/produto/rtx4060ti?origem=telegram_canal_alheio',
    affiliate_link: 'https://www.kabum.com.br/produto/rtx4060ti?tag=promoradar-20',
    telegram_msg_id: 10430,
    source_name: 'Radar Gamer BR',
    status: 'pending',
    published_at: null,
    created_at: new Date(Date.now() - 8 * 60 * 1000).toISOString(), // 8 min atrás
  },
  {
    id: 'pend-002',
    title: 'Echo Dot 5ª Geração Smart Speaker com Alexa Som Potente e Sensor de Temperatura',
    price_current: 269.10,
    price_original: 429.00,
    discount_pct: 37,
    store: 'Amazon',
    category: 'eletronicos',
    image_url: 'https://images.unsplash.com/photo-1543512214-318c7553f230?w=600&auto=format&fit=crop&q=80',
    original_link: 'https://www.amazon.com.br/dp/B09B8V1LZ3?tag=link_bruto_telegram',
    affiliate_link: 'https://www.amazon.com.br/dp/B09B8V1LZ3?tag=promoradar-20',
    telegram_msg_id: 10431,
    source_name: 'Promos VIP Tech',
    status: 'pending',
    published_at: null,
    created_at: new Date(Date.now() - 14 * 60 * 1000).toISOString(), // 14 min atrás
  },
  {
    id: 'pend-003',
    title: 'Aspirador de Pó Vertical sem Fio Electrolux Ergorapido 2 em 1 Bateria Lithium',
    price_current: 589.90,
    price_original: 899.90,
    discount_pct: 34,
    store: 'Magalu',
    category: 'casa-e-cozinha',
    image_url: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=600&auto=format&fit=crop&q=80',
    original_link: 'https://www.magazineluiza.com.br/aspirador-electrolux?utm_source=telegram_grupo',
    affiliate_link: 'https://www.magazineluiza.com.br/aspirador-electrolux?tag=promoradar-20',
    telegram_msg_id: 10432,
    source_name: 'Achados & Cupons BR',
    status: 'pending',
    published_at: null,
    created_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  },
  {
    id: 'pend-004',
    title: 'Teclado Mecânico Gamer Redragon Kumara Switch Outemu Blue RGB ABNT2',
    price_current: 189.90,
    price_original: 299.00,
    discount_pct: 36,
    store: 'Mercado Livre',
    category: 'informatica',
    image_url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80',
    original_link: 'https://produto.mercadolivre.com.br/MLB-teclado-kumara?p=antigo_afiliado',
    affiliate_link: 'https://produto.mercadolivre.com.br/MLB-teclado-kumara?tag=promoradar-20',
    telegram_msg_id: 10433,
    source_name: 'Radar Gamer BR',
    status: 'pending',
    published_at: null,
    created_at: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
  },
  {
    id: 'pend-005',
    title: 'Smartwatch Amazfit Bip 5 Tela 1.91" Chamadas Bluetooth GPS Bateria 10 Dias',
    price_current: 349.00,
    price_original: 599.00,
    discount_pct: 42,
    store: 'Amazon',
    category: 'eletronicos',
    image_url: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&auto=format&fit=crop&q=80',
    original_link: 'https://www.amazon.com.br/dp/B0CG6W7XYZ?tag=outro_grupo_tg_21',
    affiliate_link: 'https://www.amazon.com.br/dp/B0CG6W7XYZ?tag=promoradar-20',
    telegram_msg_id: 10434,
    source_name: 'Promos VIP Tech',
    status: 'pending',
    published_at: null,
    created_at: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
  },
  {
    id: 'pend-006',
    title: 'Cadeira Gamer ThunderX3 TGC12 Revestimento em Poliuretano e Apoio de Braço 2D',
    price_current: 899.90,
    price_original: 1499.00,
    discount_pct: 40,
    store: 'Kabum',
    category: 'games',
    image_url: 'https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=600&auto=format&fit=crop&q=80',
    original_link: 'https://www.kabum.com.br/produto/cadeira-tgc12?afiliado=tg_raw',
    affiliate_link: 'https://www.kabum.com.br/produto/cadeira-tgc12?tag=promoradar-20',
    telegram_msg_id: 10435,
    source_name: 'Radar Gamer BR',
    status: 'pending',
    published_at: null,
    created_at: new Date(Date.now() - 70 * 60 * 1000).toISOString(),
  },
];

// Grupos-fonte do Telegram monitorados pela automação Telethon em Python
export const MOCK_TELEGRAM_SOURCES: TelegramSource[] = [
  {
    id: 'src-01',
    name: 'Promos VIP Tech',
    channel_username: '@promosviptech',
    is_active: true,
    total_captured: 142,
    last_activity_at: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    description: 'Canal focado em eletrônicos, smartphones e gadgets importados.',
  },
  {
    id: 'src-02',
    name: 'Achados & Cupons BR',
    channel_username: '@achadosecuponsbr',
    is_active: true,
    total_captured: 89,
    last_activity_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    description: 'Ofertas diárias de casa, cozinha, moda e eletrodomésticos.',
  },
  {
    id: 'src-03',
    name: 'Radar Gamer BR',
    channel_username: '@radargamerbr',
    is_active: true,
    total_captured: 64,
    last_activity_at: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    description: 'Hardware, placas de vídeo, consoles, periféricos e jogos.',
  },
];

// Métricas de engajamento do painel administrativo
export const MOCK_METRICS: AdminMetrics = {
  total_pending: 6,
  published_today: 18,
  clicks_week: 3420,
  approval_rate_pct: 84,
  total_approved: 126,
  total_rejected: 24,
  clicks_by_day: [
    { date: '2026-09-06', clicks: 390, label: 'Dom' },
    { date: '2026-09-07', clicks: 450, label: 'Seg' },
    { date: '2026-09-08', clicks: 520, label: 'Ter' },
    { date: '2026-09-09', clicks: 480, label: 'Qua' },
    { date: '2026-09-10', clicks: 610, label: 'Qui' },
    { date: '2026-09-11', clicks: 580, label: 'Sex' },
    { date: '2026-09-12', clicks: 390, label: 'Sáb' },
  ],
  offers_by_store: [
    { store: 'Amazon', count: 58 },
    { store: 'Mercado Livre', count: 42 },
    { store: 'Kabum', count: 35 },
    { store: 'Magalu', count: 28 },
    { store: 'Shopee', count: 18 },
  ],
  offers_by_category: [
    { category: 'Eletrônicos', count: 54 },
    { category: 'Informática', count: 46 },
    { category: 'Games', count: 32 },
    { category: 'Casa & Cozinha', count: 29 },
    { category: 'TV & Áudio', count: 20 },
  ],
  status_distribution: [
    { status: 'published', label: 'Publicadas', count: 110, color: '#10b981' },
    { status: 'pending', label: 'Pendentes', count: 6, color: '#f59e0b' },
    { status: 'rejected', label: 'Rejeitadas', count: 24, color: '#ef4444' },
  ],
  top_clicked_offers: [
    { ...MOCK_OFFERS[2], click_count: 842 }, // Galaxy S24 Ultra
    { ...MOCK_OFFERS[1], click_count: 615 }, // PS5 Slim
    { ...MOCK_OFFERS[0], click_count: 489 }, // Smart TV 55
    { ...MOCK_OFFERS[3], click_count: 320 }, // Air Fryer
    { ...MOCK_OFFERS[4], click_count: 275 }, // Monitor AOC
  ],
};
