import { CouponItem } from '@/types/coupon';

export const MOCK_COUPONS: CouponItem[] = [
  {
    id: 'coup-ml-1',
    store: 'Mercado Livre',
    store_slug: 'mercadolivre',
    discount_text: '10% OFF',
    rule_text: 'Em todo o site',
    code: 'MELI10',
    affiliate_url: 'https://www.mercadolivre.com.br',
    category: 'todas',
    verified: true,
    description: 'Válido em compras acima de R$ 99 com entrega rápida.',
  },
  {
    id: 'coup-amz-1',
    store: 'Amazon',
    store_slug: 'amazon',
    discount_text: '10% OFF',
    rule_text: 'Em todo o site',
    code: 'AMAZON10',
    affiliate_url: 'https://www.amazon.com.br',
    category: 'todas',
    verified: true,
    description: 'Válido para produtos selecionados vendidos e entregues pela Amazon.',
  },
  {
    id: 'coup-ml-2',
    store: 'Mercado Livre',
    store_slug: 'mercadolivre',
    discount_text: '25% OFF',
    rule_text: 'Em todo o site',
    code: 'SUPER25',
    affiliate_url: 'https://www.mercadolivre.com.br',
    category: 'eletronicos',
    verified: true,
    description: 'Cupom especial em eletrônicos e informática.',
  },
  {
    id: 'coup-mgl-1',
    store: 'Magazine Luiza',
    store_slug: 'magalu',
    discount_text: 'R$Grátis OFF',
    rule_text: 'Em todo o site',
    code: 'MAGALUGRATIS',
    affiliate_url: 'https://www.magazineluiza.com.br',
    category: 'todas',
    verified: true,
    description: 'Frete Grátis exclusivo para compras realizadas pelo app.',
  },
  {
    id: 'coup-kbm-1',
    store: 'Kabum',
    store_slug: 'kabum',
    discount_text: '15% OFF',
    rule_text: 'Hardware e Periféricos',
    code: 'KABUM15',
    affiliate_url: 'https://www.kabum.com.br',
    category: 'informatica',
    verified: true,
    description: 'Válido em placas de vídeo, processadores e monitores.',
  },
  {
    id: 'coup-shp-1',
    store: 'Shopee',
    store_slug: 'shopee',
    discount_text: 'R$ 20 OFF',
    rule_text: 'Compras acima de R$ 100',
    code: 'SHOPEE20',
    affiliate_url: 'https://www.shopee.com.br',
    category: 'todas',
    verified: true,
    description: 'Cupom oficial de desconto em lojas oficiais da Shopee.',
  },
  {
    id: 'coup-sam-1',
    store: 'Samsung',
    store_slug: 'samsung',
    discount_text: '10% OFF',
    rule_text: 'Linha Galaxy',
    code: 'GALAXY10',
    affiliate_url: 'https://www.samsung.com/br',
    category: 'eletronicos',
    verified: true,
    description: 'Desconto extra em smartphones Galaxy S24, Z Flip e tablets.',
  },
  {
    id: 'coup-cb-1',
    store: 'Casas Bahia',
    store_slug: 'casasbahia',
    discount_text: 'R$ 50 OFF',
    rule_text: 'Compras acima de R$ 500',
    code: 'CB50',
    affiliate_url: 'https://www.casasbahia.com.br',
    category: 'casa-e-cozinha',
    verified: true,
    description: 'Desconto direto no carrinho em eletrodomésticos e smart TVs.',
  },
];
