"""
Dados de referência e fallback para cupons, lojas, categorias e ofertas simuladas.
Garante paridade com os dados do frontend (mock-data.ts e mock-coupons.ts).
"""

PYTHON_MOCK_COUPONS = [
    {
        "id": "coup-ml-1",
        "store": "Mercado Livre",
        "store_slug": "mercadolivre",
        "discount_text": "10% OFF",
        "rule_text": "Em todo o site",
        "code": "MELI10",
        "affiliate_link": "https://www.mercadolivre.com.br",
        "category": "todas",
        "valid_until": "31/12/2026",
        "description": "Válido em compras acima de R$ 99 com entrega rápida.",
        "is_verified": True,
    },
    {
        "id": "coup-amz-1",
        "store": "Amazon",
        "store_slug": "amazon",
        "discount_text": "10% OFF",
        "rule_text": "Em todo o site",
        "code": "AMAZON10",
        "affiliate_link": "https://www.amazon.com.br",
        "category": "todas",
        "valid_until": "31/12/2026",
        "description": "Válido para produtos selecionados vendidos e entregues pela Amazon.",
        "is_verified": True,
    },
    {
        "id": "coup-ml-2",
        "store": "Mercado Livre",
        "store_slug": "mercadolivre",
        "discount_text": "25% OFF",
        "rule_text": "Em todo o site",
        "code": "SUPER25",
        "affiliate_link": "https://www.mercadolivre.com.br",
        "category": "eletronicos",
        "valid_until": "30/11/2026",
        "description": "Cupom especial em eletrônicos e informática.",
        "is_verified": True,
    },
    {
        "id": "coup-mgl-1",
        "store": "Magazine Luiza",
        "store_slug": "magalu",
        "discount_text": "Frete Grátis",
        "rule_text": "Em todo o site",
        "code": "MAGALUGRATIS",
        "affiliate_link": "https://www.magazineluiza.com.br",
        "category": "todas",
        "valid_until": "15/10/2026",
        "description": "Frete Grátis exclusivo para compras realizadas pelo app.",
        "is_verified": True,
    },
    {
        "id": "coup-kbm-1",
        "store": "Kabum",
        "store_slug": "kabum",
        "discount_text": "15% OFF",
        "rule_text": "Hardware e Periféricos",
        "code": "KABUM15",
        "affiliate_link": "https://www.kabum.com.br",
        "category": "informatica",
        "valid_until": "20/12/2026",
        "description": "Válido em placas de vídeo, processadores e monitores.",
        "is_verified": True,
    },
    {
        "id": "coup-shp-1",
        "store": "Shopee",
        "store_slug": "shopee",
        "discount_text": "R$ 20 OFF",
        "rule_text": "Compras acima de R$ 100",
        "code": "SHOPEE20",
        "affiliate_link": "https://www.shopee.com.br",
        "category": "todas",
        "valid_until": "31/12/2026",
        "description": "Cupom oficial de desconto em lojas oficiais da Shopee.",
        "is_verified": True,
    },
    {
        "id": "coup-sam-1",
        "store": "Samsung",
        "store_slug": "samsung",
        "discount_text": "10% OFF",
        "rule_text": "Linha Galaxy",
        "code": "GALAXY10",
        "affiliate_link": "https://www.samsung.com/br",
        "category": "eletronicos",
        "valid_until": "31/10/2026",
        "description": "Desconto extra em smartphones Galaxy S24, Z Flip e tablets.",
        "is_verified": True,
    },
    {
        "id": "coup-cb-1",
        "store": "Casas Bahia",
        "store_slug": "casasbahia",
        "discount_text": "R$ 50 OFF",
        "rule_text": "Compras acima de R$ 500",
        "code": "CB50",
        "affiliate_link": "https://www.casasbahia.com.br",
        "category": "casa-e-cozinha",
        "valid_until": "30/09/2026",
        "description": "Desconto direto no carrinho em eletrodomésticos e smart TVs.",
        "is_verified": True,
    },
]

PYTHON_MOCK_CATEGORIES = [
    {"name": "Smartphones", "slug": "smartphones", "count": 24, "description": "Celulares, iPhones e acessórios móveis."},
    {"name": "Informática", "slug": "informatica", "count": 19, "description": "Notebooks, hardware, monitores e periféricos."},
    {"name": "Eletrônicos", "slug": "eletronicos", "count": 32, "description": "Smartwatches, tablets, caixas de som e fones."},
    {"name": "Games", "slug": "games", "count": 15, "description": "Consoles PS5, Xbox, Switch e jogos."},
    {"name": "Casa e Cozinha", "slug": "casa-e-cozinha", "count": 28, "description": "Air fryers, eletroportáteis e cafeteiras."},
    {"name": "TV e Áudio", "slug": "tv-e-audio", "count": 12, "description": "Smart TVs 4K, soundbars e home theaters."},
    {"name": "Moda", "slug": "moda", "count": 45, "description": "Tênis, vestuário e acessórios."},
]

PYTHON_MOCK_STORES = [
    {"name": "Amazon", "slug": "amazon", "count": 48, "url": "https://www.amazon.com.br"},
    {"name": "Mercado Livre", "slug": "mercadolivre", "count": 62, "url": "https://www.mercadolivre.com.br"},
    {"name": "Magazine Luiza", "slug": "magalu", "count": 35, "url": "https://www.magazineluiza.com.br"},
    {"name": "Kabum", "slug": "kabum", "count": 29, "url": "https://www.kabum.com.br"},
    {"name": "Shopee", "slug": "shopee", "count": 41, "url": "https://www.shopee.com.br"},
    {"name": "AliExpress", "slug": "aliexpress", "count": 33, "url": "https://pt.aliexpress.com"},
    {"name": "Casas Bahia", "slug": "casasbahia", "count": 22, "url": "https://www.casasbahia.com.br"},
    {"name": "Samsung", "slug": "samsung", "count": 18, "url": "https://www.samsung.com/br"},
]
